---
.github/workflows/ci.yaml:
    acceptance_matrix:
      set:
      - ---el8
      - el9
      - ---debian-11
      - ---ubuntu-2004
      - ---ubuntu-2204
.github/workflows/release.yaml:
  username: ghoneycutt
.gitlab-ci.yml:
  delete: true

.pdkignore:
  paths:
    - '/rakelib/'

.rubocop.yml:
  default_configs:
    Layout/HashAlignment:
      Enabled: false
    Layout/IndentationConsistency:
      Enabled: false
    Layout/FirstHashElementIndentation:
      Enabled: false
    Layout/SpaceAfterNot:
      Enabled: false
    Layout/SpaceInsideParens:
      Enabled: false
    RSpec/EmptyLineAfterFinalLet:
      Enabled: false
    RSpec/ExampleWording:
      Enabled: false
    RSpec/HookArgument:
      Enabled: false
    RSpec/ImplicitExpect:
      Enabled: false
    RSpec/NamedSubject:
      Enabled: false
    Style/AndOr:
      Enabled: false
    Style/HashSyntax:
      Enabled: false
    Style/NegatedIf:
      Enabled: false
    Style/RegexpLiteral:
      Enabled: false
    Style/TrailingCommaInArrayLiteral:
      Enabled: false
    Style/TrailingCommaInHashLiteral:
      Enabled: false

.travis.yml:
  unmanaged: true

appveyor.yml:
  unmanaged: true

data/common.yaml:
  unmanaged: true

Rakefile:
  default_disabled_lint_checks:
    - '80chars'
    - '140chars'

spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
  mock_with: ':rspec'
